In [2]:
import torch

In [4]:
import imageio

In [5]:
img_arr = imageio.imread('d4/image-dog/bobby.jpg')

C:\Users\justm\AppData\Local\Temp\ipykernel_10904\2935192797.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('d4/image-dog/bobby.jpg')


In [6]:
img_arr.shape

(720, 1280, 3)

In [ ]:
img_arr, img_arr.shape

In [9]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)
out.shape

torch.Size([3, 720, 1280])

In [10]:
out[:3]

tensor([[[ 77,  77,  78,  ..., 118, 117, 116],
         [ 75,  76,  77,  ..., 118, 117, 116],
         [ 74,  75,  77,  ..., 117, 117, 116],
         ...,
         [215, 216, 217,  ..., 174, 176, 176],
         [215, 216, 217,  ..., 173, 174, 174],
         [215, 216, 217,  ..., 159, 158, 158]],

        [[ 45,  45,  46,  ...,  78,  77,  76],
         [ 43,  44,  45,  ...,  78,  77,  76],
         [ 39,  40,  43,  ...,  80,  78,  77],
         ...,
         [165, 166, 167,  ..., 121, 123, 123],
         [165, 166, 167,  ..., 123, 124, 124],
         [165, 166, 167,  ..., 109, 107, 107]],

        [[ 22,  22,  21,  ...,  52,  51,  50],
         [ 20,  21,  20,  ...,  52,  51,  50],
         [ 17,  18,  18,  ...,  51,  49,  48],
         ...,
         [ 78,  79,  80,  ...,  51,  53,  53],
         [ 78,  79,  80,  ...,  54,  55,  55],
         [ 78,  79,  80,  ...,  40,  41,  41]]], dtype=torch.uint8)

In [13]:
batch = torch.zeros([3, 3, 256, 256], dtype=torch.uint8)

In [42]:
import glob

folder_path = 'd4/image-cats'  # Replace with the actual folder path

png_files = glob.glob(folder_path + '/*.png')

for i, file in enumerate(png_files):
    with open(file, 'rb') as f:
        arr = imageio.imread(f)
    img = torch.from_numpy(arr)
    img = img.permute(2, 0, 1) #pytorch expect color x height x width
    # if(i == 1):
    #     print(img.shape)
    batch[i] = img    


C:\Users\justm\AppData\Local\Temp\ipykernel_10904\1051617319.py:9: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  arr = imageio.imread(f)


In [43]:
batch[0]

tensor([[[156., 152., 124.,  ..., 150., 149., 158.],
         [174., 134., 165.,  ..., 120., 136., 138.],
         [127., 156., 107.,  ..., 131., 143., 164.],
         ...,
         [116., 130., 129.,  ..., 127., 118., 112.],
         [129., 130., 123.,  ..., 115., 121., 114.],
         [129., 123., 118.,  ..., 113., 121., 120.]],

        [[139., 135., 109.,  ..., 135., 135., 147.],
         [160., 119., 149.,  ..., 105., 122., 124.],
         [113., 140.,  90.,  ..., 118., 129., 152.],
         ...,
         [ 99., 110., 111.,  ..., 117., 108., 103.],
         [111., 111., 106.,  ..., 106., 112., 105.],
         [111., 104., 102.,  ..., 103., 110., 111.]],

        [[129., 123.,  98.,  ..., 131., 132., 145.],
         [155., 110., 137.,  ..., 102., 119., 121.],
         [104., 132.,  80.,  ..., 112., 125., 146.],
         ...,
         [ 93., 108., 105.,  ..., 125., 115., 108.],
         [108., 108.,  98.,  ..., 110., 117., 110.],
         [107.,  98.,  95.,  ..., 108., 115., 116.]]]

In [44]:
batch = batch.float()

In [45]:
batch.mean(1).shape

torch.Size([3, 256, 256])

In [46]:
batch.std(1).shape

torch.Size([3, 256, 256])

In [47]:
# batch = (batch - batch.mean(1)) / batch.std(1)

In [49]:
batch.shape

torch.Size([3, 3, 256, 256])

In [50]:
for i in range(batch.shape[1]):
    m = batch[:, i, :, :].mean()
    s = batch[:, i, :, :].std()
    batch[:, i, :, :] = (batch[:, i, :, :] - m) / s

In [52]:
batch[:,1,:,:].shape

torch.Size([3, 256, 256])

In [62]:
dir_path = 'd4/volumetric-dicom/2-LUNG 3.0  B70f-04083'
vol_arr = imageio.volread(dir_path, 'dicom')
vol_arr.shape


Reading DICOM (examining files): 1/99 files (1.0%)

99/99 files (100.0%)
  Found 1 correct series.
Reading DICOM (loading data): 75/99  (75.899/99  (100.0%)


(99, 512, 512)

In [63]:
vol = torch.from_numpy(vol_arr).float().unsqueeze_(0)
vol.shape

torch.Size([1, 99, 512, 512])

In [93]:
import pandas as pd
df = pd.read_csv('d4/tabular-wine/winequality-white.csv', sep=';')


In [103]:
df_data = df.iloc[:,:-1]
df_target = df.iloc[:,-1]
df_data[:2], 

(   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0            7.0              0.27         0.36            20.7      0.045   
 1            6.3              0.30         0.34             1.6      0.049   
 
    free sulfur dioxide  total sulfur dioxide  density   pH  sulphates  alcohol  
 0                 45.0                 170.0    1.001  3.0       0.45      8.8  
 1                 14.0                 132.0    0.994  3.3       0.49      9.5  ,)

In [109]:
df_target[10]

5

In [97]:
# cat = pd.Categorical(df_target, range(0,11))
# pd.get_dummies(cat, )


In [98]:
# df.drop('quality', axis=1, inplace=True)
# df.apply(lambda x: (x - x.mean()) / x.std())
# df = pd.concat([df, pd.get_dummies(cat)], axis=1)
# # df - df.mean() / df.std()

In [100]:
target = df_target.to_numpy()
target = torch.from_numpy(target)
target_onehot = torch.zeros(target.shape[0], 10)
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [111]:
target_onehot[10]

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [112]:
data = df_data.to_numpy()
data = torch.from_numpy(data).float()
data_mean = data.mean(0)
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [113]:
data_var = data.var(0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [114]:
data.shape

torch.Size([4898, 11])

In [115]:
data_normm = (data-data_mean)/torch.sqrt(data_var)
data_normm

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7997e-02,  ...,  7.3995e-01,
          1.3417e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

In [123]:
bikes_df = pd.read_csv('d4/bike-sharing-dataset/hour-fixed.csv')

In [124]:
bikes_df['dteday'] = pd.to_datetime(bikes_df['dteday'])  # Convert the 'dteday' column to datetime if it's not already
bikes_df['dteday'] = bikes_df['dteday'].dt.day  # Extract the day of the month and assign it to a new column 'day_of_month'


In [125]:
bikes_df

instant  dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0            1       1       1   0     1   0        0        6           0   
1            2       1       1   0     1   1        0        6           0   
2            3       1       1   0     1   2        0        6           0   
3            4       1       1   0     1   3        0        6           0   
4            5       1       1   0     1   4        0        6           0   
...        ...     ...     ...  ..   ...  ..      ...      ...         ...   
17515    17375      31       1   1    12  19        0        1           1   
17516    17376      31       1   1    12  20        0        1           1   
17517    17377      31       1   1    12  21        0        1           1   
17518    17378      31       1   1    12  22        0        1           1   
17519    17379      31       1   1    12  23        0        1           1   

       weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0               1  0.24  0.2879  0.81     0.0000       3          13   16  
1               1  0.22  0.2727  0.80     0.0000       8          32   40  
2               1  0.22  0.2727  0.80     0.0000       5          27   32  
3               1  0.24  0.2879  0.75     0.0000       3          10   13  
4               1  0.24  0.2879  0.75     0.0000       0           1    1  
...           ...   ...     ...   ...        ...     ...         ...  ...  
17515           2  0.26  0.2576  0.60     0.1642      11         108  119  
17516           2  0.26  0.2576  0.60     0.1642       8          81   89  
17517           1  0.26  0.2576  0.60     0.1642       7          83   90  
17518           1  0.26  0.2727  0.56     0.1343      13          48   61  
17519           1  0.26  0.2727  0.65     0.1343      12          37   49  

[17520 rows x 17 columns]

In [172]:
bikes_df.astype('float32').values.shape

(17520, 17)

In [177]:
bikes = torch.from_numpy(bikes_df.astype('float32').values).float().contiguous() 
#stride information will be wrong if contiguous() isn't called

In [178]:
bikes_df.values.shape

(17520, 17)

In [179]:
len(bikes_df.columns)

17

In [180]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

In [181]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [182]:
daily_bikes = daily_bikes.transpose(1, 2)

In [183]:
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 17, 24]), (408, 1, 17))

In [184]:
# import numpy as np
# bikes_numpy = np.loadtxt(
#     'd4/bike-sharing-dataset/hour-fixed.csv',
#     dtype=np.float32,
#     delimiter=",",
#     skiprows=1,
#     converters={1: lambda x: float(x[8:10])})
# bikes_z = torch.from_numpy(bikes_numpy)
# bikes_z.shape, bikes_z.stride()

In [186]:
daily_bikes.shape[:2] + (4,)

torch.Size([730, 17, 4])

In [191]:
daily_bikes[:,9].shape

torch.Size([730, 24])

In [194]:
onehot = torch.zeros(daily_bikes.shape[0], 4, daily_bikes.shape[2])
onehot.scatter_(1, daily_bikes[:,9].unsqueeze(1).long() - 1, 1.0)

tensor([[[1., 1., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0

In [195]:
onehot[0]

tensor([[1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
         0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.]])

In [196]:
daily_bikes = torch.cat((daily_bikes, onehot), dim=1)

In [197]:
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 21, 24]), (504, 24, 1))